### ISSUE TITLE
Terrors of Abaddon requires a Black Mirror

### ISSUE THREAD

**Issue by ThreeLeggedTable** [andreanespeca/StarBreach#3]
It looks like the Terrors of Abaddon are set to have a minimum of one Black Mirrors. I believe this should be a maximum of one. 

Edit: I’ll just add this on here. The Champion of Horror should have a secondary weapon of Claws and Fangs (instead of Fire Breath.)

**Comment by andreanespeca** [comment]
Black mirrors fixed thanks to report that! The Champion of horror is different between deluxe and free rulebook will correct as soon as the errata comes out. Thanks
P.S correction will be only released after the errata all together
