### ISSUE TITLE
Doomsayer not a psycher

### ISSUE THREAD

**Issue by dikarika** [andreanespeca/StarBreach#4]
![Capture+_2020-03-03-20-23-36](https://user-images.githubusercontent.com/60942419/75835426-e232b500-5d8c-11ea-9f20-d4e32b926a56.png)
Looks like according to Facebook the upcoming FAQ removes psycher from doomsayers. Apparently only the deluxe edition has this error and will be fixed.

**Comment by andreanespeca** [comment]
Yes this will be fixed together with the errata released, which should be within this week.
Thanks to report this back!
