### ISSUE TITLE
Corrected Values

### ISSUE THREAD

**Issue by PsiOvertake** [andreanespeca/StarBreach#7]
Thank you again for hosting and maintaining this!  Your lists helped me realize a few mistakes in my armies as well.  Here's what I found after going through my lists:
Corrupted L'Orani - L'Orani Warlock's 3rd ability should cost 3uc
Intergalactic Marshals - name should be Intergalactic Marshals
	-Marshal's 3rd skill should cost 3UC
	-Cyborg Specialist rocket launcher should cost 0
Legion of Mankind - Sergeant's 3rd skill (instead of 2nd) should cost 0
L'Orani Empire - L'Orani Prince's 3rd skill should cost 3UC and grenades should cost 0
Hive Cult - Brood Daughter should get relic for free
Machine Cult - Cyborg Prophet's 3rd skill should cost 3UC
Nomadic Raiders - Wandering Mage relics should be at-cost
	-Merchant Marine primary weapon should be free
Terror Legion - Terror Sergeant's 3rd skill (instead of 2nd) should cost 0
	-Warlock's primary weapon options should include Corrupted Claws instead of Corrupted Gauntlet
The Dark Path - Dark Assault Trooper's Auto Targeting System should be free
The Path - Knight of the Path's 3rd skill (instead of the 1st) should cost 0
	-Disciple's relic says RelicS
The Resistance - Paramedic should cost 8UC
U'rak Warlords - Should be lowercase r for U'rak
	-Big Bad Boss' 3rd skill should cost 3UC

Not sure how to address the skills thing when it's prescribed.  Maybe a radio button?

**Comment by andreanespeca** [comment]
As i release the corrections i close this issue please create a new issue if you need to reply to some of the point, thanks
